driver: oracle
connectionString : (DESCRIPTION=
  (ADDRESS_LIST=
  (ADDRESS=(protocol=TCP)(host=127.0.0.1)(port=1521))
  )
  (CONNECT_DATA=
  (SERVICE_NAME=XE)
  ))
IP : 127.0.0.1
port : 1521
username: system
password: r7V96AGy69X
database: XE
