0d7cd9d221395e1e:
  id: 0d7cd9d221395e1e
  token: f5e4beba-78c9-4a2d-aa40-2f7d80c38ffa
  name: mosquitto_test
  config:
  - sensorId: 1
    schema:
      valueType: 4
      unit: 1
      typeId: 65296
      name: dcsn_cntry
    event:
      change: true
      timeSec: 30
      lowerThreshold: null
      upperThreshold: null
  - sensorId: 2
    schema:
      valueType: 4
      unit: 1
      typeId: 65296
      name: thy_cmpr
    event:
      change: true
      timeSec: 30
      lowerThreshold: null
      upperThreshold: null
  - sensorId: 3
    schema:
      valueType: 4
      unit: 1
      typeId: 65296
      name: rcv
    event:
      change: true
      timeSec: 30
      lowerThreshold: null
      upperThreshold: null
  - sensorId: 4
    schema:
      valueType: 4
      unit: 1
      typeId: 65296
      name: nc_sf
    event:
      change: true
      timeSec: 30
      lowerThreshold: null
      upperThreshold: null
  - sensorId: 5
    schema:
      valueType: 4
      unit: 1
      typeId: 65296
      name: ndstry_scnd
    event:
      change: true
      timeSec: 30
      lowerThreshold: null
      upperThreshold: null
  - sensorId: 6
    schema:
      valueType: 1
      unit: 1
      typeId: 65296
      name: ndstry_scnd
    event:
      change: true
      timeSec: 30
      lowerThreshold: null
      upperThreshold: null
  - sensorId: 7
    schema:
      valueType: 2
      unit: 1
      typeId: 65296
      name: ndstry_scnd
    event:
      change: true
      timeSec: 30
      lowerThreshold: null
      upperThreshold: null
  state: new
  data: []
  error: ""
