config:
    - sensor:
          ID: sensorId
          Topic: topic_test
          Value: objeto_valor
          Name: objeto_nome
          Timestamp: objeto_timestamp
    - sensor:
          ID:  sensorId
          Topic: knot
          Value: objeto_valor
          Name: objeto_nome
          Timestamp: objeto_timestamp
