config:
  - 1:
    Topic: topic
    Value: data.0.valor
    Timestamp: data.0.timestamp
  - 2:
    Topic: topic2
    Value: data.0.valor
    Timestamp: data.0.timestamp
  - 3:
    Topic: topic
    Value: data.1.valor
    Timestamp: data.1.timestamp
  - 4:
    Topic: topic2
    Value: data.1.valor
    Timestamp: data.1.timestamp
